---
- hosts: localhost
  user: prateekbaheti
  connection: local
  vars_files:
    - vars/main.yml
  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']